### ISSUE TITLE
[Fixed]Crash app Drawable-v24, i need explan why?

### ISSUE THREAD

**Issue by haitrvn** [mitchtabian/Dagger-Examples#6]
I don't know why? but it can fix by move all files in drawable-v24 to drawable.
![1](https://user-images.githubusercontent.com/52912440/71303973-5e566700-23f2-11ea-84cb-fd7bb01f65cf.png)
![2](https://user-images.githubusercontent.com/52912440/71303974-5e566700-23f2-11ea-840b-5cdf4e228cdf.png)
> Error report:

`
12-21 12:58:13.054 10546-10546/com.codingwithmitch.daggerpractice E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.codingwithmitch.daggerpractice, PID: 10546
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.codingwithmitch.daggerpractice/com.codingwithmitch.daggerpractice.ui.auth.AuthActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f070072
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f070072
        at android.content.res.Resources.getValue(Resources.java:1351)
        at android.content.res.Resources.getDrawable(Resources.java:804)
        at android.content.Context.getDrawable(Context.java:458)
        at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:454)
        at com.codingwithmitch.daggerpractice.di.AppModule.provideAppDrawable(AppModule.java:55)
        at com.codingwithmitch.daggerpractice.di.AppModule_ProvideAppDrawableFactory.provideAppDrawable(AppModule_ProvideAppDrawableFactory.java:29)
        at com.codingwithmitch.daggerpractice.di.AppModule_ProvideAppDrawableFactory.get(AppModule_ProvideAppDrawableFactory.java:19)
        at com.codingwithmitch.daggerpractice.di.AppModule_ProvideAppDrawableFactory.get(AppModule_ProvideAppDrawableFactory.java:10)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.codingwithmitch.daggerpractice.di.DaggerAppComponent$AuthActivitySubcomponentImpl.injectAuthActivity(DaggerAppComponent.java:269)
        at com.codingwithmitch.daggerpractice.di.DaggerAppComponent$AuthActivitySubcomponentImpl.inject(DaggerAppComponent.java:259)
        at com.codingwithmitch.daggerpractice.di.DaggerAppComponent$AuthActivitySubcomponentImpl.inject(DaggerAppComponent.java:222)
        at dagger.android.DispatchingAndroidInjector.maybeInject(DispatchingAndroidInjector.java:113)
        at dagger.android.DispatchingAndroidInjector.inject(DispatchingAndroidInjector.java:134)
        at dagger.android.AndroidInjection.inject(AndroidInjection.java:59)
        at dagger.android.support.DaggerAppCompatActivity.onCreate(DaggerAppCompatActivity.java:43)
        at com.codingwithmitch.daggerpractice.ui.auth.AuthActivity.onCreate(AuthActivity.java:55)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

**Comment by mDNA1198** [comment]
The different drawable folders are for providing different screen densities for device compatibility and for different Android versions.

The resources in "drawable" will work in most android versions but the one's in "drawable-24" will work on android version 24 and above only.

**Comment by ghost** [comment]
Invalidate cache and restart
